# -*- coding: utf-8 -*-
"""PostNet on DNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NgChdZiAjEcXJpY0k8a2YzUAnpTg7BRd
"""

# from google.colab import drive
# drive.mount('/content/drive')

# Import section
import os
import keras
import scipy.io
import statistics
import numpy as np
import tensorflow as tf
from tensorflow import keras
from keras import optimizers
from keras import backend as K
from collections import Counter
from keras.optimizers import Adam
from keras.models import Sequential
from sklearn.metrics import f1_score, confusion_matrix
def confusion_matrix_binary(y_true, y_pred):
  y_true = np.asarray(y_true).reshape(-1).astype(np.int32)
  y_pred = np.asarray(y_pred).reshape(-1).astype(np.int32)
  tn = int(np.sum((y_true == 0) & (y_pred == 0)))
  fp = int(np.sum((y_true == 0) & (y_pred == 1)))
  fn = int(np.sum((y_true == 1) & (y_pred == 0)))
  tp = int(np.sum((y_true == 1) & (y_pred == 1)))
  return np.array([[tn, fp], [fn, tp]], dtype=np.int64)

def f1_score_binary(y_true, y_pred):
  y_true = np.asarray(y_true).reshape(-1).astype(np.int32)
  y_pred = np.asarray(y_pred).reshape(-1).astype(np.int32)
  tp = float(np.sum((y_true == 1) & (y_pred == 1)))
  fp = float(np.sum((y_true == 0) & (y_pred == 1)))
  fn = float(np.sum((y_true == 1) & (y_pred == 0)))
  precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
  recall    = tp / (tp + fn) if (tp + fn) > 0 else 0.0
  if (precision + recall) == 0:
    return 0.0
  return 2.0 * precision * recall / (precision + recall)
from keras.utils import to_categorical
from tensorflow.keras.preprocessing.sequence import pad_sequences
from keras.callbacks import ModelCheckpoint ,EarlyStopping
from keras.layers import TimeDistributed, Dense, Dropout, BatchNormalization, Dropout, Masking

#loading data

def dl(path):
  if path.endswith('.npz'):
    data = np.load(path)
  else:
    data = scipy.io.loadmat(path)
  print(data.keys())
  x = data['feature']; y = data['label'];
  if 'test' in path and 'TDNN' in path:
    w = data['w']
    test_ind = data['test_ind']
    return x, y, w, test_ind
  elif 'test' in path and 'TDNN' not in path:
    w = data['w']
    return x, y, w
  else:
    return x, y.T

# ---- helpers to load/concat your PART files (only change made) ----
def dl_train_parts(part_paths):
  xs, ys = [], []
  for p in part_paths:
    x, y = dl(p)         # returns x, y.T for train files
    xs.append(x)
    ys.append(y.flatten())
  x_cat = np.vstack(xs)
  y_cat = np.concatenate(ys)
  return x_cat, y_cat

def dl_test_parts(part_paths):
  xs, ys, ws, tis = [], [], [], []
  offset = 0
  for p in part_paths:
    x, y, w, ti = dl(p)  # returns x, y, w, test_ind for test files
    xs.append(x)
    ys.append(y.flatten())
    ws.append(w.flatten())
    ti = np.asarray(ti).flatten().astype(int)
    if ti.size > 0:
      tis.append(ti + offset)  # offset indices to global
    offset += x.shape[0]
  x_cat = np.vstack(xs)
  y_cat = np.concatenate(ys)
  w_cat = np.concatenate(ws)
  ti_cat = np.concatenate(tis) if len(tis) > 0 else np.array([], dtype=int)
  return x_cat, y_cat, w_cat, ti_cat
# -------------------------------------------------------------------

def convert_function(arr):
  temp=[]
  for i in arr:
    if i>0.5:
      temp.append(1)
    else:
      temp.append(0)
  return temp

def calculate_accuracy(arr1, arr2):
  count=0
  for itr1, itr2 in zip(arr1, arr2):
    if itr1==itr2:
      count+=1
  return count/len(arr1)

def make_partitions(arr_words, arr_labels):
  v=[]
  np.array(v)
  temp=[]
  for i in range(len(arr_words)-1):
    word=arr_words[i]
    next_word=arr_words[i+1]
    temp.append(arr_labels[i][0])
    if word!=next_word:
      numpy_temp=np.array(temp)
      temp_max=np.amax(numpy_temp)
      numpy_temp=np.divide(numpy_temp, temp_max)
      v=np.concatenate((v, numpy_temp), axis=None)
      temp.clear()
    if (i==len(arr_words)-2):
      temp.append(arr_labels[i+1][0])
      numpy_temp=np.array(temp)
      temp_max=np.amax(numpy_temp)
      numpy_temp=np.divide(numpy_temp, temp_max)
      v=np.concatenate((v, numpy_temp), axis=None)
      temp.clear()
  v1=[]
  for i in v:
    if i==1:
      v1.append(1)
    else:
      v1.append(0)
  return v1


def make_partitions2(arr_words, arr_labels):
  v=[]
  np.array(v)
  temp=[]
  for i in range(len(arr_words)-1):
    word=arr_words[i]
    next_word=arr_words[i+1]
    temp.append(arr_labels[i])
    if word!=next_word:
      numpy_temp=np.array(temp)
      temp_max=np.amax(numpy_temp)
      numpy_temp=np.divide(numpy_temp, temp_max)
      v=np.concatenate((v, numpy_temp), axis=None)
      temp.clear()
    if (i==len(arr_words)-2):
      temp.append(arr_labels[i+1])
      numpy_temp=np.array(temp)
      temp_max=np.amax(numpy_temp)
      numpy_temp=np.divide(numpy_temp, temp_max)
      v=np.concatenate((v, numpy_temp), axis=None)
      temp.clear()
  v1=[]
  for i in v:
    if i==1:
      v1.append(1)
    else:
      v1.append(0)
  return v1

def sampling(args):
    z_mean, z_log_sigma = args
    epsilon = K.random_normal(shape=(K.shape(z_mean)[0], latent_dim), mean=0., stddev=0.004)
    return z_mean + K.exp(z_log_sigma) * epsilon

def normalization(feats,avg,std):
  ii=0
  for v in feats:
    # print(len(v))
    feats[ii] = np.divide((v-avg),std)
    ii = ii+1
  return feats

# === CHANGED: use your TDNN *TRAIN PARTS* instead of single GER TDNN file ===
# === CHANGED: use your TDNN *TRAIN PARTS* instead of single GER TDNN file ===
train_parts = [
  #"/srv/scratch/z5353712/data/thesis_code/tdnn/feats_WLM_train_TDNN_split_part01.mat",
  #"/srv/scratch/z5353712/data/thesis_code/tdnn/feats_WLM_train_TDNN_split_part02.mat",
  #"/srv/scratch/z5353712/data/thesis_code/tdnn/feats_WLM_train_TDNN_split_part03.mat",
  #"/srv/scratch/z5353712/data/thesis_code/tdnn/feats_WLM_train_TDNN_split_part04.mat",
  #"/srv/scratch/z5353712/data/thesis_code/tdnn/feats_WLM_train_TDNN_split_part05.mat",
  #"/srv/scratch/z5353712/data/thesis_code/en_tdnn/en_wavlm_train_data_TDNN_split_part01.mat",
  #"/srv/scratch/z5353712/data/thesis_code/en_tdnn/en_wavlm_train_data_TDNN_split_part02.mat",
  #"/srv/scratch/z5353712/data/thesis_code/en_tdnn/en_wavlm_train_data_TDNN_split_part03.mat",
  #"/srv/scratch/z5353712/data/thesis_code/en_tdnn/en_wavlm_train_data_TDNN_split_part04.mat",
  #"/srv/scratch/z5353712/data/thesis_code/en_tdnn/en_wavlm_train_data_TDNN_split_part05.mat",
  #"/srv/scratch/z5353712/data/thesis_code/en_tdnn/en_wavlm_train_data_TDNN_split_part06.mat",
  #"/srv/scratch/z5353712/data/thesis_code/en_tdnn/en_wavlm_train_data_TDNN_split_part07.mat",
  #"/srv/scratch/speechdata/Abdulrahman_ML_data/myst_train_TDNN.npz"
  "/srv/scratch/speechdata/Abdulrahman_ML_data/myst_2to4_train_TDNN.npz"
]

print('Classification with:::::: feats_ar_train_TDNN_split_part**')

xtrain1, ytrain1 = dl_train_parts(train_parts)

train_size = xtrain1.shape[0]
print(train_size)

avg_trainfeat1=np.mean(xtrain1, axis=0)
std_trainfeat1=np.std(xtrain1, axis=0)

#test_path = '/srv/scratch/z5353712/data/thesis_code/ar_en_test_wlm.mat'
#test_path = '/srv/scratch/z5353712/data/thesis_code/en_wavlm_test_data.mat'
#test_path = '/srv/scratch/z5353712/data/thesis_code/feats_WLM_test.mat'
#test_path = '/srv/scratch/speechdata/Abdulrahman_ML_data/myst_test.npz'
#test_path = '/srv/scratch/speechdata/Abdulrahman_ML_data/myst_2to4_test.npz'
test_path = '/srv/scratch/speechdata/Abdulrahman_ML_data/ogi_2to4_test.npz'
print('test file:::::::',os.path.basename(test_path))

xtest1, ytest1, wtest1 = dl(test_path);

xtest_ac = normalization(xtest1,avg_trainfeat1,std_trainfeat1)

xtrain1 = normalization(xtrain1,avg_trainfeat1,std_trainfeat1)
print(xtrain1.shape)

woPP=[]; wPP=[]
accuracy_all_folds_wopp = []; accuracy_all_folds_wpp = []; f1score_all_folds_wopp = []; f1score_all_folds_wpp = [];
accuracy_all_folds_wopp_a = [];  accuracy_all_folds_wpp_a  = [];  f1score_all_folds_wopp_a  = [];  f1score_all_folds_wpp_a  = [];


print(xtrain1.shape)
print(ytrain1.shape)

highest_accuracy = 0.0

# === CHANGED: use your TDNN *TEST PARTS* instead of single GER TDNN file ===
test_parts = [
  #"/srv/scratch/z5353712/data/thesis_code/ar_en_TDNN_WLM_test.npz",
  #"/srv/scratch/z5353712/data/thesis_code/en_wavlm_test_data_TDNN_small.npz",
  #"/srv/scratch/z5353712/data/thesis_code/feats_ar_test_TDNN_combined.mat",
  #"/srv/scratch/speechdata/Abdulrahman_ML_data/myst_test_TDNN.npz"
  #"/srv/scratch/speechdata/Abdulrahman_ML_data/myst_2to4_test_TDNN.npz"
  "/srv/scratch/speechdata/Abdulrahman_ML_data/ogi_2to4_test_TDNN.npz"
]

# TDNN train/test via parts
# (kept identical logic below; only these loads changed)
# Re-loads that appear later in the original notebook:
xtrain1, ytrain1 = dl_train_parts(train_parts)
xtest_ac, ytest, wtest, test_ind = dl_test_parts(test_parts)
xtrain1 = xtrain1
ytrain1 = ytrain1
# === END change ===

# DNN test file kept exactly as in original code
#xt, yt, wt = dl("/srv/scratch/z5353712/data/thesis_code/ar_en_test_wlm.mat")
#xt, yt, wt = dl("/srv/scratch/z5353712/data/thesis_code/en_wavlm_test_data.mat")
#xt, yt, wt = dl("/srv/scratch/z5353712/data/thesis_code/feats_WLM_test.mat")
#xt, yt, wt = dl("/srv/scratch/speechdata/Abdulrahman_ML_data/myst_test.npz")
#xt, yt, wt = dl("/srv/scratch/speechdata/Abdulrahman_ML_data/myst_2to4_test.npz")
xt, yt, wt = dl("/srv/scratch/speechdata/Abdulrahman_ML_data/ogi_2to4_test.npz")

# ---- Shape fixes to match your expected layout ----
# Train (expect: labels (N,1))
if ytrain1.ndim == 1:
    ytrain1 = ytrain1.reshape(-1, 1)            # (2442771, 1)

# TDNN test (expect: labels (1,N), w (1,#words), test_ind (K,))
ytest = np.asarray(ytest)
if ytest.ndim == 1:
    ytest = ytest.reshape(1, -1)                 # (1, 528381)
elif ytest.shape[1] == 1:                        # if (N,1) -> (1,N)
    ytest = ytest.reshape(1, -1)

wtest = np.asarray(wtest)
if wtest.ndim == 1:
    wtest = wtest.reshape(1, -1)                 # (1, 187010)

test_ind = np.asarray(test_ind).reshape(-1)      # (341371,)

# DNN test (expect: features (187010,1024), labels (187010,1), word count (1,187010))
yt = np.asarray(yt)
if yt.ndim == 1:
    yt = yt.reshape(-1, 1)                       # (187010, 1)
elif yt.shape[0] == 1:                           # if (1,187010) -> (187010,1)
    yt = yt.T

wt = np.asarray(wt)
if wt.ndim == 1:
    wt = wt.reshape(1, -1)                       # (1, 187010)

print("TDNN train data features:", xtrain1.shape, "\nTDNN train data labels:", ytrain1.shape)
print("TDNN test data features:", xtest_ac.shape, "\nTDNN test data labels: ",ytest.shape, "\nTDNN test data syllable count: ",wtest.shape, "\nDNN test data features: ",xt.shape, "\nDNN test data labels: ",yt.shape, "\nDNN test data word count: ", wt.shape)

yt = yt.flatten()
wtest = wtest.flatten()
test_ind = test_ind.flatten()
print(yt.shape, wtest.shape, test_ind.shape)

original_dim = 1024

woPP = []
wPP = []
accuracy_all_folds_wopp_a = []
accuracy_all_folds_wpp_a = []
f1score_all_folds_wopp_a = []
f1score_all_folds_wpp_a = []
accuracy_all_folds_wpp_a1 = []
j=0

train_size = xtrain1.shape[0]
ytrain1 = ytrain1.flatten()

#xtrain1 = xtrain1[:1508354,:]
for j in range(0,2): # folds
  xval_ac = xtrain1[(train_size*j)//2:(train_size*(j+1))//2];
  print(xval_ac.shape)
  yval_ac = ytrain1[(train_size*j)//2:(train_size*(j+1))//2]
  xtra_ac = np.concatenate((xtrain1[:(train_size*j)//2], xtrain1[((train_size*(j+1))//2):]), axis=0);
  ytra_ac = np.concatenate((ytrain1[:(train_size*j)//2], ytrain1[((train_size*(j+1))//2):]), axis=0)
  print("hi",xtra_ac.shape, xval_ac.shape)

  max_sequence_length = 4
  print(f"\nFold {j + 1} - Max Sequence Length: {max_sequence_length}")

  model1 = Sequential()
  model1.add(Masking(mask_value=-1, input_shape=(max_sequence_length, original_dim)))
  model1.add(TimeDistributed(Dense(1024, activation='relu', kernel_initializer='he_normal')))
  model1.add(TimeDistributed(BatchNormalization()))
  model1.add(TimeDistributed(Dropout(0.2)))
  #model1.add(TimeDistributed(Dense(512, activation='relu', kernel_initializer='he_normal')))
  #model1.add(TimeDistributed(BatchNormalization()))
  #model1.add(TimeDistributed(Dropout(0.2)))
  #model1.add(TimeDistributed(Dense(256, activation='relu', kernel_initializer='he_normal')))
  #model1.add(TimeDistributed(BatchNormalization()))
  #model1.add(TimeDistributed(Dropout(0.2)))
  #model1.add(TimeDistributed(Dense(128, activation='relu', kernel_initializer='he_normal')))
  #model1.add(TimeDistributed(BatchNormalization()))
  #model1.add(TimeDistributed(Dropout(0.2)))
  #model1.add(TimeDistributed(Dense(64, activation='relu', kernel_initializer='he_normal')))
  #model1.add(TimeDistributed(BatchNormalization()))
  #model1.add(TimeDistributed(Dropout(0.1)))
  model1.add(TimeDistributed(Dense(1, activation='sigmoid', name='stress')))

  model1.load_weights('best_model_weights_WLM12.h5')

  model1.compile(optimizer=Adam(learning_rate=0.005), loss='binary_crossentropy', metrics=['accuracy'])


  sequence_length = 4
  num_sequences = len(xtra_ac) // sequence_length

  xtra_ac_reshaped = xtra_ac[:num_sequences * sequence_length].reshape((num_sequences, sequence_length, 1024))
  print(xtra_ac_reshaped.shape)

  ytra_ac_modified = np.zeros((num_sequences, sequence_length, 1), dtype=int)
  print(ytra_ac.shape)


  ytra_ac_reshaped = ytra_ac.reshape((num_sequences, sequence_length, 1))

  ytra_ac_modified[:, :, 0] = ytra_ac_reshaped[:, :, 0]


  num_sequences_val = len(xval_ac) // sequence_length

  xval_ac_reshaped = xval_ac[:num_sequences_val * sequence_length].reshape((num_sequences_val, sequence_length, 1024))

  i=0; label = 0

  yval_ac_modified = np.zeros((num_sequences_val, sequence_length, 1), dtype=int)
  yval_ac_reshaped = yval_ac.reshape((num_sequences_val, sequence_length, 1))
  yval_ac_modified[:, :, 0] = yval_ac_reshaped[:, :, 0]

  early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

  model1.fit(xtra_ac_reshaped, ytra_ac_modified, epochs=200, batch_size=32, validation_data=(xval_ac_reshaped, yval_ac_modified), callbacks=[early_stopping])


  num_sequences_test = len(xtest_ac) // sequence_length

  xtest_ac_modified = xtest_ac[:num_sequences_test * sequence_length].reshape((num_sequences_test, sequence_length, 1024))
  i=0; label = 0
  print("before the predictions")
  print(xtest_ac_modified.shape)
  pred_output1= model1.predict(xtest_ac_modified)
  #print(pred_output1)
  # Your input array
  array_of_arrays = pred_output1

  flattened_array = array_of_arrays.reshape(-1, array_of_arrays.shape[-1])

  result_array_ = [flattened_array[i] for i in range(len(flattened_array)) if i not in test_ind]
  result_array = np.array([array.tolist() for array in result_array_])

  # print(result_array, yt)
  # print(result_array.shape, yt.shape)
  yt = yt.T
  y_pred_a = np.where(result_array > 0.5, 1, 0)

  print(y_pred_a)
  accuracy = calculate_accuracy(y_pred_a, yt)
  print("============......",accuracy)
  post_labels=make_partitions(wtest, result_array)
  post_l = np.array(post_labels)
  swapped_array = np.where(post_l == 0, 1.0, 0.0)


  outdir = "/home/z5353712/thesis/Interspeech2024_PostNet-main/Codes/Supervised"
  os.makedirs(outdir, exist_ok=True)
  if j == 0:
        np.save(os.path.join(outdir, "y_pred_a7.npy"),  post_l.astype(np.int64))
  elif j == 1:
        np.save(os.path.join(outdir, "y_pred_a8.npy"),  post_l.astype(np.int64))
  else:
       	np.save(os.path.join(outdir, "y_pred_a9.npy"),  post_l.astype(np.int64))


  accuracy_xtest_a = calculate_accuracy(post_l, yt)
  accuracy_xtest_a1 = calculate_accuracy(swapped_array, yt)
  print(accuracy_xtest_a,"original")
  F1_score_WoPP_a = f1_score(yt, y_pred_a, average="binary")
  F1_score_WPP_a = f1_score(yt, post_labels, average="binary")
  print(f"Fold {j+1} confusion matrix (WoPP):\n", confusion_matrix(yt, y_pred_a))
  print(f"Fold {j+1} confusion matrix (WPP):\n", confusion_matrix(yt, post_labels))
  accuracy_all_folds_wopp_a.append(round(accuracy * 100, 3))
  accuracy_all_folds_wpp_a.append(round(accuracy_xtest_a * 100, 3))
  accuracy_all_folds_wpp_a1.append(round(accuracy_xtest_a1 * 100, 3))
  f1score_all_folds_wopp_a.append(round(F1_score_WoPP_a * 100, 3))
  f1score_all_folds_wpp_a.append(round(F1_score_WPP_a * 100, 3))

print(accuracy_all_folds_wopp_a)
print(f1score_all_folds_wopp_a)

